### ISSUE TITLE
Minecraft is crashing with Shader

### ISSUE THREAD

**Issue by Steinhaeger88** [LunaPixelStudios/Better-MC#1068]
Hello,

I have the problem that Minecraft crashes when using it with shaders.
I first had the problem that Minecraft wasn't running at all, after I allocated more RAM (8G) it works.
The shader that comes with the modpack crashes a short time after activation, the Sildurs Vibrant Shaders v1.27 Medium runs better, but also crashes.
From the feeling whenever new shunks are loaded, I have already reduced the range in the settings.

I hope someone can help
[hs_err_pid10208 new shader.txt](https://github.com/LunaPixelStudios/Better-MC/files/10805717/hs_err_pid10208.new.shader.txt)

**Comment by chorbintime** [comment]
1) Download an adoptium release for Java (recommended but not required):
- Java 11 (https://adoptium.net/temurin/releases/?version=11) for versions 1.16.5 and below (can also use 8 if its not working)
- Java 18 (https://adoptium.net/temurin/releases/?version=18) for any versions newer (or 17 if 18 doesn't work)
- Consider installing the JRE instead of the JDK for a smaller file size

2) When installing through adoptium, make sure that Add to PATH and Set JAVA_HOME variable are both set to be installed (please see https://imgur.com/a/jPu1h7h for how that would look)

3) Check if java has been correctly installed by running java --version (or java -version on older versions), and seeing if the output is correct (see https://imgur.com/a/OWcoq4p for an example of the output)
- NOTE: 64 bit versions of java ALWAYS have '64-bit Server VM' in the version output. If that is not there, you have installed a 32-BIT version!! If you're getting Out of Memory errors or any other errors, PLEASE install 64-bit

4) If the output isn't as intended, you have 2 options.
i) Delete ALL other java versions from your PC (ONLY recommended if you don't need them)
ii) Redirect your launcher/server to use your new installation of Java

Method i
1) Uninstall any other java program listed in your programs list (differs by OS, please find a guide for your own OS if you don't know)
2) Attempt to re-use the command mentioned above (if the output is now correct, which it should be, you are ready to go)

Method ii
1) For a server, please modify the $Java/JAVA variable (found in your startup script depending on ps1/sh) to the path of your java installation. For windows, this path is usually found in "Program Files/Eclipse Adoptium/version_of_java/bin"
2) For a client, depending on whether you use CurseForge, GD, or AT, the process is slightly different. Please see a guide for each respective launcher on how to change the java version.
