### ISSUE TITLE
Crash-ingame

### ISSUE THREAD

**Issue by Dr-SamuRAY** [LunaPixelStudios/Better-MC#1099]
### Describe the Bug

The game crash randomly every 20minutes 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

1.19.2 v15

### Optifine

No

### Other Mods

no
[hs_err_pid10988.log](https://github.com/LunaPixelStudios/Better-MC/files/10891349/hs_err_pid10988.log)

**Comment by chorbintime** [comment]
not a modpack issue.

switch to Adoptium Java 18. Here is a step by step taken from our discord:
1) Download an adoptium release for Java (recommended but not required):
- Java 11 (https://adoptium.net/temurin/releases/?version=11) for versions 1.16.5 and below (can also use 8 if its not working)
- Java 18 (https://adoptium.net/temurin/releases/?version=18) for any versions newer (or 17 if 18 doesn't work)
- Consider installing the JRE instead of the JDK for a smaller file size

2) When installing through adoptium, make sure that Add to PATH and Set JAVA_HOME variable are both set to be installed (please see https://imgur.com/a/jPu1h7h for how that would look)

3) Check if java has been correctly installed by running java --version (or java -version on older versions), and seeing if the output is correct (see https://imgur.com/a/OWcoq4p for an example of the output)
- NOTE: 64 bit versions of java ALWAYS have '64-bit Server VM' in the version output. If that is not there, you have installed a 32-BIT version!! If you're getting Out of Memory errors or any other errors, PLEASE install 64-bit

4) If the output isn't as intended, you have 2 options.
i) Delete ALL other java versions from your PC (ONLY recommended if you don't need them)
ii) Redirect your launcher/server to use your new installation of Java

Method i
1) Uninstall any other java program listed in your programs list (differs by OS, please find a guide for your own OS if you don't know)
2) Attempt to re-use the command mentioned above (if the output is now correct, which it should be, you are ready to go)
