### ISSUE TITLE
Ping-Wheel not installed on Server

### ISSUE THREAD

**Issue by LukenSkyne** [LunaPixelStudios/Better-MC#1170]
Hello! Author of [Ping-Wheel](https://www.curseforge.com/minecraft/mc-mods/ping-wheel) here, thanks for including my mod in your fabric pack!

I recently received feedback that some players are having trouble getting the mod to work on Better MC servers. After investigating the issue, I discovered that the mod is not included on the server by default.

To address this, I've tested manually adding the mod to a clean install of a Better MC [FABRIC] server, and it seems to be working fine.
If there is any problems with the mod being installed on the server, I'll be happy to help!

**Comment by chorbintime** [comment]
The tool we use to create our serverpacks, Server Pack Creator, was automatically excluding Ping Wheel because it incorrectly detected it as a clientside only. The creator of Server Pack Creator has been notified about this and this issue will not persist in newer versions of our modpacks.

Thank you for the report. I apologize for any inconvenience this may have caused.
