### ISSUE TITLE
Server not starting

### ISSUE THREAD

**Issue by lucasschmitz-dev** [LunaPixelStudios/Better-MC#1210]
### Describe the Bug

Similar Issue to #1208
now I am using Adoptium Java 18.

While Startup the Server is always carshing.

I am using a dedicated Server from Hetzner with:
AMD Ryzen™ 5 3600CPU6 cores / 12 threads @ 3.6 GHzGeneration:Matisse (Zen 2)
RAM64 GB DDR4 RAMDrives
2 x 512 GB NVMe SSD

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://gist.github.com/lucasschmitz-dev/b7d2ecdcf893b70f7f5a96982b0e1ab2

### Operating System

Ubuntu-2204-jammy-amd64-base

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Better MC [FORGE] 1.19.2 v14

### Optifine

No

**Comment by Frontear** [comment]
I believe this issue relates to [this bug for java](https://bugs.openjdk.org/browse/JDK-8306444). From what I can see you have very high memory objects which almost indicates a memory leak, and this bug explicitly mentions that.

As for a solution, um, I think you could try using Java 20 to run the server once, then once it crashes (because the mods arent compatible), switch back to 18. I can't promise you itll work 100% but your error is happening when forge installer tries to setup the server, which it should be fine on java 20 for.

**Comment by Frontear** [comment]
Also alternatively, if you dont want to go down that route, you could maybe add a flag to the server start script to allocate a high amount of memory for the forge installer. A memory leak could simply be ignored if you have enough memory to spare

**Comment by lucasschmitz-dev** [comment]
The same issue is also happening on jdk 20, either on Oracle or on Temurin. More RAM also doesnt solve the issue.
I also tried the vanilla minecraft server from their website and I got the same error. This isn't modpack related.
Sometimes it gets a bit further, sometime it crashed instantly.

Maybe you could help me, where should I ask for help then?

**Comment by Frontear** [comment]
Java 20 wont work at all because iirc Mixin and quite a few mods are not yet compatible. Downgrade down to 17
