### ISSUE TITLE
Error code 1 when launching

### ISSUE THREAD

**Issue by DGMexe** [LunaPixelStudios/Better-MC#1224]
### Describe the Bug

Error occurs when I try to launch Minecraft with the Better MC Forge BMC3 1.19.2 pack. Tried to update graphics drivers, update Java, uninstall every Minecraft launcher with .minecraft, reinstall CurseForge and all to no avail. After launching, the window closes for a few seconds only to pop up again with an error message.

### Reproduction Steps

1. Install Minecraft
2. Install CurseForge
3. Install BMC3 1.19.2 Forge pack
4. Click "Play" on CurseForge (opens Minecraft Launcher)
5. Click "Launch" in Minecraft Launcher
...

### Screenshots and Videos
N/A
### Crash Report or Log

https://pastebin.com/C2PxcvSS

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v14

### Optifine

No

**Comment by chorbintime** [comment]
Taken from our discord, which you can join at https://lunapixel.studio/discord

If you are having issues launching 1.19.2 modpacks, please do the following:
- Update drivers
- Update Windows
- Use ATLauncher instead of Curseforge (Read #faq for more info)
- Use Java 18 instead of Java 17 (Read the performance guide linked in #faq for more info)
- Free up storage space

If nothing else works, run the ``!glfw`` command in #bots and follow the steps there.
If you have any questions, please ask in the channel that corresponds to the modpack you are playing.

**Comment by DGMexe** [comment]
Will try, thanks!

**Comment by DGMexe** [comment]
ATLauncher works like a charm! Thanks a lot!
