### ISSUE TITLE
Can't open the modpack via Curseforge

### ISSUE THREAD

**Issue by LucasCastilho7** [LunaPixelStudios/Better-MC#1231]
### Describe the Bug

I try to open the modpack via Curseforge and just doesn't work, but if i try to open manually installing the modpack it works. I want to play with my friends but for this i need to open the modpack via Curseforge, otherwise i can't enter in the server.

Tried everything, even game minecraft 10 gigabytes of ram to use and even so didn't work.

### Reproduction Steps

1. 
2. 
3.
...

### Crash Report or Log

https://gist.github.com/LucasCastilho7/f5b5eb952c2eacbc00d26bb5991b1a32#file-crash_report-txt

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

No

**Comment by chorbintime** [comment]
You can not 'manually install' a modpack. It doesn't work that way.

Taken from our Discord, that can be joined using https://www.lunapixel.studio/discord

If you are having issues launching 1.19.2 modpacks, please do the following:
- Update drivers
- Update Windows
- Use ATLauncher instead of Curseforge (Read #faq for more info)
- Use Java 18 instead of Java 17 (Read the performance guide linked in #faq for more info)
- Free up storage space

If nothing else works, run the ``!glfw`` command in #bots and follow the steps there.
If you have any questions, please ask in the channel that corresponds to the modpack you are playing.
