### ISSUE TITLE
Unable to find foundry?

### ISSUE THREAD

**Issue by Crossaintdog** [LunaPixelStudios/Better-MC#1261]
### Describe the Bug

Hello Better Minecraft Creators, where tf did the Dungeons Arise, Foundry, go? I updated the game once and all of the sudden I cannot find or "/locate" the foundry. Please fix this as it was my favorite dungeon you added and now that its gone, the mod is no real challenge. I miss old better minecraft. Thank you. -Axel Skinner (Crossaintdog)

### Reproduction Steps

1. Add
2. It
3. Back
...

### Screenshots and Videos

I could go around most the map and it won't work.

![FoundryLocate](https://github.com/LunaPixelStudios/Better-MC/assets/136279142/990f8eb4-fbca-4af8-be5b-90afdc8e0f98)
![NotLoadingFoundry](https://github.com/LunaPixelStudios/Better-MC/assets/136279142/5a8b44d1-0402-44cc-97c3-cd92846709bf)

### Operating System

Windows 11

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

1.16.5

### Optifine

I used Optifine

### Other Mods

nope.

**Comment by chorbintime** [comment]
the foundry is disabled, this is intentional and its been a thing for months 

Optifine is incompatible with all of our modpacks and crashes the game on startup when installed. There is no reason to use Optifine for any Minecraft versions 1.16.5 or newer. Do not expect support from any mod developers when Optifine is installed.
