### ISSUE TITLE
BetterMC Fabric 1.20.1 v8 crash on create world

### ISSUE THREAD

**Issue by KB-Q** [LunaPixelStudios/Better-MC#1352]
### Describe the Bug

Crashes when clicking create world

### Reproduction Steps

1. Download modpack
2. Click create world
3. Crash
...

### Crash Report or Log

https://mclo.gs/yvkQ3CR, https://mclo.gs/b4Xoqqz

### Operating System

MacOS Catalina 13.5

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

1.20.1 v8

**Comment by Frontear** [comment]
This crash is due to a bug with that _specific_ version of Java 17. Please update to a newer version, or use Java 18

**Comment by chorbintime** [comment]
Follow the performance guide for steps on how to do the above https://github.com/LunaPixelStudios/Medieval-MC/wiki/Performance-Guide

**Comment by pironc** [comment]
Still no fix ? No news ? Nothing ? People are not able to play ? Still happening on macOS 14 Sonoma

**Comment by chorbintime** [comment]
> Still no fix ? No news ? Nothing ? People are not able to play ? Still happening on macOS 14 Sonoma
> 
> Edit : refer to my fix in #1424

The fix is literally one reply above yours. Your fix is the exact same as what we said.

**Comment by pironc** [comment]
It's nowhere near explicit.
Using macOS you have to dig to be able to find what "Java" is actually referring to.

I had "Java 8" for something to work yet it didn't, because it wasn't the proper "Java" and because nobody clearly explains nothing and the wiki doesn't specify ARM installation and not even Windows (ARM Java 8 JRE is **unavailable officially** and has to be downloded from **Azul**.

I had another encounter with Java 18 and specified a 3rd party and using a launcher to set the custom Java JRE path in order to use it.

So no, it was not fixed for everyone, and someone without much knowledge would still be stuck.

**Comment by chorbintime** [comment]
The guide specifically tells you where to install Java, and also says to not use Java 8.
