### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by TempystWin** [LunaPixelStudios/Better-MC#1379]
### Describe the Bug

I launch the game, it dies. Starts loading mods and poofs.

### Reproduction Steps

1.Launch game
2.Blue screen
3.dissapoint
...

### Crash Report or Log

https://gist.github.com/TempystWin/308f41170e1e232caf1f93930e814084

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 *ANY*

**Comment by chorbintime** [comment]
You (likely) need to update your graphics drivers in order to resolve the crash. Here's how to go about doing that!

**1. Identify your graphics card**
_if you already know skip to the next step_
- Open task manager
- Navigate to the "Performance" tab (on Windows 11 this is the button that looks like a heart pulse)
- Press the GPU 0 graph and read your GPU from the top right

**Note:**
*In some cases you may see a GPU 0 and GPU 1. This means your CPU has its own GPU, as well as an external one. You probably want GPU 1 (which is usually the external), but you can ask staff to clarify if necessary.*

**2. Download your drivers from the manufacturers site**
Depending on what you read before, you likely need drivers from either AMD, Intel, or NVIDIA

**AMD**: <https://www.amd.com/en/support> 
**Intel**: <https://www.intel.com/content/www/us/en/download-center/home.html> 
**NVIDIA**: <https://www.nvidia.com/Download/index.aspx?lang=en-us> 

**Note:**
- *For NVIDIA you want to select "Game Ready Driver (GRD)" (this is the default option) for the best performance. Once installing you'd probably prefer downloading GeForce Experience, which will notify you when there's an available drivers update.*
- *For Intel, you probably want to press "Get Started" under the "Automatically update your drivers and software", which will simplify the process and update everything automatically*
- *For AMD you probably want to just press "Download Windows Drivers", which will download something called AMD Adrenaline, which will update your drivers automatically.*

**3. Run the installation, restart your computer, and try playing MC again**
- At this point, hopefully your Minecraft is running. If it still does not work, please post any new logs and staff will help assist you with finding the right solution.
