### ISSUE TITLE
game crashing on launch

### ISSUE THREAD

**Issue by j701411** [LunaPixelStudios/Better-MC#1430]
### Describe the Bug

keep crashing on launch for some reason and getting error code 1

### Reproduction Steps

1.launch game
2.crash

### Crash Report or Log

https://pastebin.com/GhZestBu

### Operating System

windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

v19

**Comment by chorbintime** [comment]
Update your GPU drivers, manually, through the vendor's website

**Comment by j701411** [comment]
I already tried updating the GPU drivers.  I also turned off the hardware acceleration.

Problem only happens with the mod.  I can run Minecraft or other mods just fine.

**Comment by j701411** [comment]
> I already tried updating the GPU drivers. I also turned off the hardware acceleration.
> 
> Problem only happens with the mod. I can run Minecraft or other mods just fine.

I already tried updating the GPU drivers. I also turned off the hardware acceleration.

Problem only happens with the mod. I can run Minecraft or other mods just fine.

**Comment by chorbintime** [comment]
Better MC is not a mod, it is a modpack.

Hardware acceleration has nothing to do with it.

The only reason this happens is due to outdated drivers. You need to update them directly through the vendor's website. 

If you're unable to get that to work, do the following:

For users who are experiencing issues with the built-in GLFW, there's a quick and easy solution for you to use the latest, bug-free GLFW that can remedy the solution.

1. Download a pre-built GLFW library from my repository at https://github.com/Frontear/glfw/releases. Ensure you download the correct file from the desription of the release. You may also compile it yourself, details can be found here: https://www.glfw.org/docs/latest/compile.html
2. Save the file in a location you can remember and will **NOT** delete (the file MUST stay there or else it will stop working)
3. In your launcher, go to the java parameters (this is the place you put your GC arguments), and add `-Dorg.lwjgl.glfw.libname="path/to/the/file"`. If, for example, you downloaded the file in your Downloads (`C:\Users\Me\Downloads\glfw3.dll`, then your argument would be `-Dorg.lwjgl.glfw.libname="C:\Users\Me\Downloads\glfw3.dll"`)

**Comment by j701411** [comment]
Thanks for the comment.  I've done all you stated, and none of that still helped.

**Comment by chorbintime** [comment]
Send a screenshot of your Args section in ATLauncher

**Comment by j701411** [comment]
-Xmx8096m -Xms256m -Dminecraft.applet.TargetDirectory="C:\Users\steves\curseforge\minecraft\Instances\Better MC [FORGE] - BMC4" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -Dsun.java2d.d3d=false  -Dorg.lwjgl.glfw.libname="C:\tmp\glfw3.dll"

![image](https://github.com/LunaPixelStudios/Better-MC/assets/140812811/282755f1-4863-4614-9c52-f14382f8e9a1)

**Comment by chorbintime** [comment]
Thats not where you change the args. Do it in the Curseforge launcher itself, and remove any other args that are present.

If the issue persists, retry the same thing on ATLauncher instead

**Comment by j701411** [comment]
Same issue...  no go.

-Dorg.lwjgl.glfw.libname="C:\tmp\glfw3.dll"

Both launchers...

**Comment by chorbintime** [comment]
Send a screenshot of your ATLauncher java args

**Comment by j701411** [comment]
As an FYI...  the GeForce new drivers just came out and I just finished installing them.  It still doesn't work.

**Comment by j701411** [comment]
![image](https://github.com/LunaPixelStudios/Better-MC/assets/140812811/ea0382d4-10b9-4d9a-900d-3f92af2b97a9)

**Comment by j701411** [comment]
[hs_err_pid25124.log](https://github.com/LunaPixelStudios/Better-MC/files/13048254/hs_err_pid25124.log)

**Comment by j701411** [comment]
fyi...
Even though I am supposed to be using the GeForce Graphics Adapter, apparently it was going to the AMD Processor and Graphics (maybe from your dll file?).  In any case, when I upgraded the AMD with the manufacter drivers, it started working.
