### ISSUE TITLE
Veridium infusion doesn't work

### ISSUE THREAD

**Issue by Lantis-Hegg** [LunaPixelStudios/Better-MC#1467]
The server console spits out an warning saying:
![image_2023-11-02_153413663](https://github.com/LunaPixelStudios/Better-MC/assets/123079950/c495538e-9771-4e0b-af3d-0d6aba5de88b)
The inventory then glitches out and will "refund" the ambrosium shard and pickaxe after grabbing from their visibly now empty inventory slots. Sometimes it will seem to work correctly on the client end but attempting to use the newly infused tool will cause it to disappear and the same thing appears in the server console.

After further investigation it appears that crafting a veridium tool will produce this warning:
![image](https://github.com/LunaPixelStudios/Better-MC/assets/123079950/ea074787-e5bb-484a-8379-5d9de9ab7800)

I do believe this is a bug because there is a quest in the quest book for infusing veridium tools.
This is a known issue among my friend group, I figured I'd raise it here cause this is where the curseforge site led me.
The specific version is BMC3 [Forge] on the latest modpack version in 1.19.2
If there's any more information needed I may have overlooked please ask.

EDIT: It works in singleplayer the issue is with the serverpack.

**Comment by chorbintime** [comment]
report it to the mod developer

**Comment by DiscoDude96** [comment]
> report it to the mod developer

I have the same problem, and I came here looking for an answer, so thanks for the "help".

**Comment by Closed-Sleet** [comment]
> report it to the mod developer

It works fine on the mods end, the issue must be within the server packs handling of infusion. Haven't tested new updates so no clue if this has actually been fixed yet. (Judging from the recent comment I'm guessing not)

If you have no intention of looking into the bug then please have this report marked properly. Easier for people looking and prevents frustration.

**Comment by chorbintime** [comment]
The serverpack does not change any mod behavior. The only purpose of the serverpack is to remove clientside-only mods that would cause a server to crash.

If an issue is only happening serverside, that would almost 100% mean it's an issue with the mod itself. At worst, it'd be a mod compatibility issue with another mod, which would still be something the original mod developer could fix.

Thank you.

**Comment by Closed-Sleet** [comment]
> The serverpack does not change any mod behavior. The only purpose of the serverpack is to remove clientside-only mods that would cause a server to crash.
> 
> If an issue is only happening serverside, that would almost 100% mean it's an issue with the mod itself. At worst, it'd be a mod compatibility issue with another mod, which would still be something the original mod developer could fix.
> 
> Thank you.

The issue **is** with the supplied server pack as it works fine in Singleplayer and over LAN.
It works client side but the servers run from the server pack will create the above error.
My guess is a missing or messed up configuration file in the server pack.
All of this information is previously stated.

Please read the whole of what the issue is before outright dismissing it. Yes the server pack **Shouldn't** change mod behavior _unless it's configured improperly or missing a required mod_.  If I've learned anything from my own ventures in both mod and modpack creation I've learned there's a lot of weird client/server mod weirdness that tends to get overlooked by developers. If you find the problem is actually elsewhere please do prove me wrong. I'm just curious as to the specific problem here at this point.

**Comment by chorbintime** [comment]
You don't know what you're talking about, and my original point still stands. LAN is completely different from hosting an actual server. The configs between the client version and the server version of the modpacks are 1:1, exactly the same.
