### ISSUE TITLE
Mac OS M1 - crash error 6 when loading a world

### ISSUE THREAD

**Issue by Ysaelya** [LunaPixelStudios/Better-MC#1479]
### Describe the Bug

Hello,

I am trying to play Better MC 4 on my MacBook M1, but the game crashes when I try to create or join a world. 
I installed Java 17 so I don't think it's a java issue.
Vanilla Minecraft is working fine, so it comes from the mode pack.

### Reproduction Steps

1. launching better MC 4 from curse forge
2. the game loads just fine, I can access the menu
3. when selecting solo or multiplayer then join a world, it instantly crashes and I have a bug report.

### Crash Report or Log

https://gist.github.com/Ysaelya/c82cc9a48ba874966ccda1540edd05a2

### Operating System

Mac OS Ventura 13.3.1

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 V19

**Comment by Ysaelya** [comment]
By looking more into this Github issues I found a solution 👍 
1. install GDL launcher and connect with microsoft account
2. install forge and then with the search bar search for the desired version of BMC
3. Install java MANUALLY (Installing the latest Temurin version (aarch64 / macOS - https://adoptium.net/en-GB/temurin/releases/?version=18&os=mac&arch=aarch64&package=any) ) 
4. In settings > Java > Java 17 select this path /Library/Java/JavaVirtualMachines/temurin-18.jre/Contents/Home/bin/java.exe
5. play !

**Comment by PatricioF8** [comment]
Hello!
I had a very similar issue on my Mac, and after a lot of trial and error, I finally found a solution that worked for me. Hopefully, it helps someone else too!

**Problem:**
When playing heavy modpacks like **Better Minecraft (BMC), Macs—especially with Apple Silicon (M1, M2…)—can have issues with certain Java runtimes.** In my case, I was using Java JDK 17 by Microsoft, and everything worked fine with BMC3 for Fabric. But when I tried to run BMC4 for Forge, the game crashed every single time I tried to create a new world.
Turns out, the **Microsoft version of Java 17 isn’t fully compatible with modded Minecraft in Forge,** especially on Apple Silicon. It causes crashes at world generation due to low-level memory access issues (SIGBUS, NoSuchMethodError, etc).

**Solution:**
Switch to **Temurin Java 17 by Adoptium.** It’s a stable, community-backed OpenJDK build that works beautifully with modded Minecraft. If you’re on a Mac with Apple Silicon (M1, M2, etc.), look for the official download page on the internet and a file of type "aarch64" of Java 17 _(This is ARM64, meaning that it is the one for Apple Silicon Macs)_. The .pkg installer is the easiest option.

Once installed, you still need to tell Minecraft to use this new Java version.
Here’s how I did it in the **CurseForge app:**
1. Open **CurseForge**
2. Go to **Settings > Minecraft**
3. Scroll to **Java Settings**
4. Click on **“Choose”** next to the Java 17 executable path
5. Select this file (or similar):
**/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java**
If you can’t find the Library folder, press **Cmd + Shift + G** in Finder and paste the path above to locate it. Additionally, research how to find the Library folder on your Mac and then choose the correct Java exec from the Temurin Version. 


**Bonus: Performance tips for Mac users playing modded!**
**1. Turn on fullscreen (seriously!)**
This made a huge difference in FPS for me. Just make sure you activate it inside Minecraft’s video settings, not just by clicking the green window button on a Mac (that isn't the true fullscreen mode!).
**2. Allocate more RAM wisely**
You can do this in CurseForge or via JVM arguments in the regular Minecraft launcher. 
Rule of thumb: allocate less than half your total RAM, ideally 6–12 GB. Minecraft can get unstable above that.
**3. Adjust video settings**
Lowering render distance, simulation distance, and graphics quality can really help in heavily modded environments.

**My setup (in case it’s helpful):**
- MacBook Pro (M2 Pro chip)
- 16 GB RAM
- Running BMC4 [Forge] and BMC3 [Fabric] with shaders without issues. I average 60-90 FPS with Low Config Shaders (Complementary Reimagined), and 120+ FPS without shaders. 

So yes—**modded Minecraft absolutely can run great on Mac!** Just takes a bit of setup and tweaking. 
I really hope this helps someone out there struggling like I was!
