### ISSUE TITLE
Server startup error

### ISSUE THREAD

**Issue by zfsbsdf** [LunaPixelStudios/Better-MC#1507]
### Describe the Bug

When I updated Better MC BMC4 [FORGE] 1.20.1 v22,The start.sh file has changed!The original version 21 of the server is still working fine,Version 22 of the server is not working properly
![TQH19R03_S9Z%R4B}P3SZFI](https://github.com/LunaPixelStudios/Better-MC/assets/113145735/cba8f751-ac52-4829-8729-f45d5f28b009)
This is my configuration variables.txt
![6A)}M4W8@ C083%{(M4$N65](https://github.com/LunaPixelStudios/Better-MC/assets/113145735/8c3ee7de-cb38-4d08-8ee0-0f2458e52081)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

BMC4 FORGE 1.20.1 Server Pack v22

**Comment by Frontear** [comment]
it looks like youre using windows. please don't use the .sh file because they're designed to be used on unix systems and not under mingw/cygwin environments on windows.

on a different note, this error is usually when you run the script with `sh` and not `bash`, because it uses bash specific syntax despite the misleading file extension.
