### ISSUE TITLE
Naturalist animations don't work

### ISSUE THREAD

**Issue by Ellivers** [LunaPixelStudios/Better-MC#1597]
### Describe the Bug

Most animation for mobs from the Naturalist mod don't play, or don't play properly. I'm aware that https://github.com/starfish-studios/Naturalist/issues/8 exists, but:
1. This issue affects this modpack by default
2. I am not using any shaders

### Screenshots and Videos

https://github.com/LunaPixelStudios/Better-MC/assets/53975650/dd76bbc5-4c58-423c-a834-86613a5dbdf1

### Operating System

Windows 10

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

BMC v24

**Comment by chorbintime** [comment]
we cant really do anything about it if its a naturalist issue, sadly

**Comment by TheRealDanini** [comment]
Adding onto this even though it was marked as completed, the issue seems to be related to a conflict within BMC rather then an issue with the naturalist mod itself. the bug appears to be related to a change within BMC2 and does not seem to be present in BMC1. (however not sure if this affects BMC 3 and 4)
As this issue describes, even with shaders disabled mobs from the naturalist mod do not appear to have animations. and this is the same case for me on BMC2.

I tested in a fresh 1.20.1 fabric instance with only naturalist installed (no shaders and same mc version BMC2 uses) and animations appeared to be working, it appears that there is a mod conflict somewhere that was not present in the previous BMC version.
