### ISSUE TITLE
Failed Registry 

### ISSUE THREAD

**Issue by KaizenCloud** [LunaPixelStudios/Better-MC#1685]
### Describe the Bug

I cant launch the world. I have BMC fabric 1.20.1 v25.  It wont let me loading into my server im using aternos. Its saying Nethersdelight is the issue. Well its saying 7 registry

### Reproduction Steps

1.have bmc fabric 1.20.1 v25 and aternos cf bmc fabric 1.20.1 v25
2.load into the world
3.youll recieve the error message
...

### Screenshots and Videos

![image_2024-05-31_074641757](https://github.com/LunaPixelStudios/Better-MC/assets/171343972/0e1995a5-cd28-415a-84ac-91ee80a29087)

### Crash Report or Log

https://mclo.gs/pdcUI9S

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

bmc v25

**Comment by chorbintime** [comment]
You don't have the same modpack installed as the server. Its likely Aternos hasn't updated yet. 

I recommend selfhosting a server using the serverpack files instead of using Aternos, as Aternos is very unreliable and laggy, and takes a long time to update.

You can safely transfer over your world by downloading the world folder from Aternos and adding it to the serverpack files.

**Comment by KaizenCloud** [comment]
![image](https://github.com/LunaPixelStudios/Better-MC/assets/171343972/0dd33337-4b36-4dab-900f-3ed44413f6e0)
Even if its saying its compatible?

**Comment by chorbintime** [comment]
alright yea this was my bad, the issue is now fixed. serverpack just got reuploaded, wait for curseforge to approve it and the issue should be gone

alternatively you can just
go to your client mods folder
copy the nethers delight mod
paste it to your server mods folder
delete the old nether delight mod that was previously in the server mods folder
