### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by veqso1x** [LunaPixelStudios/Better-MC#1687]
### Describe the Bug

Cant join my server (Aternos) since the new BetterMC FABRIC (1.20.1) v25 was released, screenshot provided below with the prompt i'm seeing.
![Screenshot 2024-05-31 184251](https://github.com/LunaPixelStudios/Better-MC/assets/140985167/de0d987e-8584-4ad4-97db-d6c2c08a0eb5)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Fabric

### Modpack Version

V25

**Comment by Snakeater32** [comment]
How

**Comment by Snakeater32** [comment]
> > same here!
> 
> i moved the "NethersDelight" file from the v24 folder into the v25 folder and it works for me

How?

**Comment by chorbintime** [comment]
The latest version of BMC2 Fabric (v25) was originally uploaded with broken server files. A fixed version of the server files were uploaded shortly after. Aternos is still using the old, broken version of the server files, which causes the "Received 7 registry entries that are unknown to this client" issue when connecting to an Aternos server.

The best solution to this issue is to simply stop using Aternos. They give no control over server files and have very lacking hardware. If you want an easy, free way to host a server then use the serverpack files on the modpack's Curseforge page and read the README file.

If you want to continue to use Aternos, please contact their support team and tell them to update the server files to the newest ones available on Curseforge.
