### ISSUE TITLE
Log in Issues

### ISSUE THREAD

**Issue by SchnozmoCosma** [LunaPixelStudios/Better-MC#1701]
### Describe the Bug

I was playing Better MC with my buddy on his world through a VPN LAN connection. Everything was fine until a couple days ago when it logged me in as another character with a different default skin as well as nothing in my inventory. I would have to repeatedly and re-launch through cursed forge. Now, no matter how many times I do this it does not work. Is my profile with everything I had deleted? I am just lost on why my game just did this/

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20

### Modloader

Forge

### Modpack Version

Better MC modpack

**Comment by chorbintime** [comment]
This is because you hosted the server using LAN. We explicitly do not offer any support for LAN because of issues like this.

The modpack has built-in free world hosting, just go to the open to lan screen and click "Share world".

You can also start a server using the server files on the modpack's Curseforge page.
