### ISSUE TITLE
Too bright 

### ISSUE THREAD

**Issue by Hegris** [LunaPixelStudios/Better-MC#1728]
### Describe the Bug

Here is example of two worlds of the same seed. Difference is that one of them HEAVY modded ( bettermc 4 forge ) and another is just iris+sodium.

Same shaderpack Complementary Unbound. I REALLY LIKE how unmodded version looks. I dont know how to explain it but it looks more smooth... SOFT.

Also seems like bettermc version looks SO BRIGHT in comparsion to vanilla one

I really wanna play bettermc cuz its all fun and interesting but shaders on this modpack are sucks for me. Complementary shaderpack is my favourite and I wanna use it for my gameplay but I cant cuz how it look

Some ideas please

1i s vanilla unmodded
2 is bettermc

screenshots were taken on the same place and with the same /time set

### Screenshots and Videos

![2024-06-29_20 54 38](https://github.com/LunaPixelStudios/Better-MC/assets/97419900/4f89f357-e510-4193-b9cd-24180037c5c9)
![2024-06-29_21 24 24](https://github.com/LunaPixelStudios/Better-MC/assets/97419900/0a15da23-a7be-4ce7-a97e-4c104fba232a)

### Operating System

windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

### Other Mods

nothing relating to grahicks
epic fight mod
weapon mastery
should camera
astikor carts

**Comment by chorbintime** [comment]
We change absolutely nothing related to lighting. The modpack ships with several shaderpacks by default which are customized to our liking, and I would suggest trying those instead of adding your own. If you do you not see these ingame it's because you didn't install correctly. Reinstall the modpack on ATLauncher.

The Epic Fight mod you added causes a ton of issues and crashes.
