### ISSUE TITLE
I cant see the minimap and i see the full name of item wich was added via mod

### ISSUE THREAD

**Issue by 646Lucas** [LunaPixelStudios/Better-MC#1730]
### Describe the Bug

If I look to the top right on the minimap I see the full name of every direction for example: gui.xaero_compass_west
The same applies to the Items wich was added via Mod for example: item.mythic_charms,experience_nuggets
I dont know how to fix this.  

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![2024-06-30_16 14 38](https://github.com/LunaPixelStudios/Better-MC/assets/174259264/1e5a86c8-461b-404f-87f5-e1eed8998a7a)

![2024-06-30_16 17 25](https://github.com/LunaPixelStudios/Better-MC/assets/174259264/a786cb4a-2e81-4e20-a268-4ca99236dcc3)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
Reinstall on ATLauncher

To install ATLauncher, do the following:
1. Go to https://atlauncher.com/download 
2. Install and run the setup, then open the program.
3. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
4. Go to the Packs tab on the right, then click "Curseforge" on the left.
5. Search the modpack you wish to download.
6. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
7. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
8. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.

To transfer your Curseforge world to ATLauncher, simply right click the modpack on Curseforge, or click the 3 dots, then click "Open Folder". Copy the Saves folder, then click "Open Folder" on ATLauncher and paste the Saves folder there.
Because ATLauncher downloads the exact same files as Curseforge does, your world will be the exact same and you will be able to join the same servers. ATLauncher also works without an internet connection (after you've installed the modpack, of course), and does not have any bloat from Overwolf. You are free to uninstall both Overwolf and Curseforge with ATLauncher installed.
