### ISSUE TITLE
No shader menu

### ISSUE THREAD

**Issue by maranzadieg23wg** [LunaPixelStudios/Better-MC#1734]
### Describe the Bug

I have installed BT mine **1.20.1** server version with all mods for **forge** with the **v28** of mod pack.
Everything works correctly, but the menu for the shaders does not appear.
I would be very grateful if you could help me, thank you very much in advance.
![imagen](https://github.com/LunaPixelStudios/Better-MC/assets/146086452/6b1d5e40-4409-4670-a373-269c1ead65ef)

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
You did not install the modpack correctly - period. No way around it. 

To install ATLauncher, do the following:
1. Go to https://atlauncher.com/download 
2. Install and run the setup, then open the program.
3. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
4. Go to the Packs tab on the right, then click "Curseforge" on the left.
5. Search the modpack you wish to download.
6. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
7. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
8. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.

To transfer your Curseforge world to ATLauncher, simply right click the modpack on Curseforge, or click the 3 dots, then click "Open Folder". Copy the Saves folder, then click "Open Folder" on ATLauncher and paste the Saves folder there.
Because ATLauncher downloads the exact same files as Curseforge does, your world will be the exact same and you will be able to join the same servers. ATLauncher also works without an internet connection (after you've installed the modpack, of course), and does not have any bloat from Overwolf. You are free to uninstall both Overwolf and Curseforge with ATLauncher installed.
