### ISSUE TITLE
Zombie Villagers are appearing as Pink/Black Blocks instead of their sprites

### ISSUE THREAD

**Issue by zhoutz21** [LunaPixelStudios/Better-MC#1737]
### Describe the Bug

Zombie Villagers are appearing as Pink/Black Blocks instead of their sprites

### Reproduction Steps

1. Find a zombie villager
2. Even on the mini map it will show as a pink sprite instead of the sprite head
3.
...

### Screenshots and Videos

![ZV Image](https://github.com/LunaPixelStudios/Better-MC/assets/174958895/34b3a434-4167-450a-a6e6-54e7d7fdd177)
![ZV mini map icon](https://github.com/LunaPixelStudios/Better-MC/assets/174958895/3df9665e-1594-42a6-ab52-81c88e0f09d0)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v28

**Comment by chorbintime** [comment]
Switching away from the launcher you are currently using would likely **fix your problem**. 
From our experience, the most stable launcher by far is ATLauncher, also known as ATL.

To install ATLauncher, do the following:
**1**. Go to <https://atlauncher.com/download> 
**2**. Install and run the setup, then open the program.
**3**. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
**4**. Go to the Packs tab on the right, then click "Curseforge" on the left.
**5**. Search the modpack you wish to download.
**6**. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
**7**. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
**8**. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.

To transfer your Curseforge world to ATLauncher, simply right click the modpack on Curseforge, or click the 3 dots, then click "Open Folder". Copy the Saves folder, then click "Open Folder" on ATLauncher and paste the Saves folder there.
Because ATLauncher downloads the exact same files as Curseforge does, your world will be the exact same and you will be able to join the same servers. ATLauncher also works without an internet connection (after you've installed the modpack, of course), and does not have any bloat from Overwolf. You are free to uninstall both Overwolf and Curseforge with ATLauncher installed.
