### ISSUE TITLE
Minecraft crashed with unknown error

### ISSUE THREAD

**Issue by HVHCs2Mirage** [LunaPixelStudios/Better-MC#1761]
### Describe the Bug

I turn on the PC, start minecraft and it says minecraft closed with an unknown error

### Reproduction Steps

1.I turn on the PC, start minecraft and it says minecraft closed with an unknown error
2.Then i deleted Java and reinstall it but minecraft didnt start
3.I redowloaded Tlauncher and Minecraft Launcher but it didnt help
...

### Screenshots and Videos

![Screenshot 2024-07-27 142131](https://github.com/user-attachments/assets/b5bcbd4c-ea4e-42e7-9ae2-5fe3a4948f77)
![Screenshot 2024-07-27 142246](https://github.com/user-attachments/assets/1fadf0f5-d1d1-4f64-93c7-df33228cc480)

### Crash Report or Log

Minecraft launcher : An unexpected issue occured and the game has crashed. Exit code -2

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

I dont have got any modpacks

### Other Mods

- ### _i dont have got any mods_![Screenshot 2024-07-27 143016](https://github.com/user-attachments/assets/d740fdb2-07f3-4d47-9c8c-93b654970fea)

**Comment by chorbintime** [comment]
TLauncher is known spyware and is also unable to install mods or modpacks correctly. For a safe, working way to install both mods and modpacks, follow the guide below:
If this command was run in response to your question/issue, it is likely because switching away from the launcher you are currently using would **fix your problem**. 
From our experience, the most stable launcher by far is ATLauncher, also known as ATL.

To install ATLauncher, do the following:
**1**. Go to <https://atlauncher.com/download> 
**2**. Install and run the setup, then open the program.
**3**. Login to your Microsoft account that owns the Java Edition of Minecraft from the Accounts tab on the right. This process is 100% safe, as it goes directly through Microsoft. ATLauncher does not see your account credentials.
**4**. Go to the Packs tab on the right, then click "Curseforge" on the left.
**5**. Search the modpack you wish to download.
**6**. Click "New Instance". Click "Ok" on the opted out mods warning, then click "Open All" on the manual download screen.
**7**. Let the mods download, ATLauncher will grab them from your Downloads folder and automatically add them to the modpack.
**8**. Go to the Instances tab, and click "Play" on the modpack you downloaded. If you ever see an "Update" button on the instance, click it.
This video explains the process: <https://youtu.be/xMYW1wMbmkM>
