### ISSUE TITLE
cant play the modpack 

### ISSUE THREAD

**Issue by Daey2** [LunaPixelStudios/Better-MC#1783]
### Describe the Bug

i loaded in the modpack but it says i cant proceed because there's a mod that's incompatible? but i didnt add any mods or change any mods either 

### Screenshots and Videos

![Capture](https://github.com/user-attachments/assets/55df76a0-4ed5-41b3-beac-7e7badd5f849)

### Operating System

Windows 10

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30.5

**Comment by chorbintime** [comment]
TLauncher is known spyware and is also unable to install mods or modpacks correctly. Because we offer no support for piracy due to Discord TOS, you will need to provide proof you own a legitimate copy of Minecraft or leave the server. For a safe, working way to install both mods and modpacks, use https://atlauncher.com/downloads
