### ISSUE TITLE
An error occured in Luna

### ISSUE THREAD

**Issue by xXKingPeenXx** [LunaPixelStudios/Better-MC#1795]
### Describe the Bug

Using Modrinth. Was working yesterday. Just wondering if its an easy fix or out of my hands to fix.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Screenshot 2024-08-16 010208](https://github.com/user-attachments/assets/0251bff0-9455-4551-8035-e1aba3ea7cc1)

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Fabric

### Modpack Version

v25

**Comment by chorbintime** [comment]
Luna World Hosting is temporarily down due to maintenance issues on our end. The ingame world hosting will be available again as soon as we're able to resolve this. ETA is 24 or so hours at most. 

If you want a free, easy alternative to hosting via Luna, you can instead host on your own computer. Follow the [guide](https://github.com/chorbintime/LPS-readme/wiki/1.21)
