### ISSUE TITLE
BMC4 (Forge) Crashing On Startup

### ISSUE THREAD

**Issue by Papotheos** [LunaPixelStudios/Better-MC#1805]
### Describe the Bug

I downloaded the Better Minecraft modpack off of ATLauncher and when i pressed play ATLauncher closed and turned back on again where i left off without any crash code. I also tried it on curseforge and it didn't work. i tried switching the version but every forge version wasn't working, only fabric.

### Reproduction Steps

I don't know what you mean by reproducing the bug so I wrote what I thought was correct.
1. Download BMC4 Modpack on ATLauncher
2. Select "Instances"
3. Hit Play under BMC4
4. Crash

### Crash Report or Log

https://paste.atlauncher.com/view/82f57e6e-23cf-4711-9395-d66fa62ecff6

### Operating System

Windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v30

**Comment by chorbintime** [comment]
You (likely) need to update your graphics drivers in order to resolve the crash. Here's how to go about doing that!

**1. Identify your graphics card**
_if you already know skip to the next step_
- Open task manager
- Navigate to the "Performance" tab (on Windows 11 this is the button that looks like a heart pulse)
- Press the GPU 0 graph and read your GPU from the top right

**Note:**
*In some cases you may see a GPU 0 and GPU 1. This means your CPU has its own GPU, as well as a dedicated one. You probably want GPU 1 (which is usually the better one), but you can ask staff to clarify if necessary.*

**2. Download your drivers from the manufacturers site**
Depending on what you read before, you likely need drivers from either AMD, Intel, or NVIDIA

**AMD**: <https://www.amd.com/en/support> 
**Intel**: <https://www.intel.com/content/www/us/en/download-center/home.html> 
**NVIDIA**: <https://www.nvidia.com/Download/index.aspx?lang=en-us> 

**Note:**
- *For NVIDIA you want to select "Game Ready Driver (GRD)" (this is the default option) for the best performance. Once installing you'd probably prefer downloading GeForce Experience, which will notify you when there's an available drivers update.*
- *For Intel, you probably want to press "Get Started" under the "Automatically update your drivers and software", which will simplify the process and update everything automatically*
- *For AMD you probably want to just press "Download Windows Drivers", which will download something called AMD Adrenaline, which will update your drivers automatically.*

**3. Run the installation, restart your computer, and try playing MC again**
- At this point, hopefully your Minecraft is running. If it still does not work, please post any new logs and staff will help assist you with finding the right solution.

**Comment by Papotheos** [comment]
> You (likely) need to update your graphics drivers in order to resolve the crash. Here's how to go about doing that!
> 
> **1. Identify your graphics card** _if you already know skip to the next step_
> 
> * Open task manager
> * Navigate to the "Performance" tab (on Windows 11 this is the button that looks like a heart pulse)
> * Press the GPU 0 graph and read your GPU from the top right
> 
> **Note:** _In some cases you may see a GPU 0 and GPU 1. This means your CPU has its own GPU, as well as a dedicated one. You probably want GPU 1 (which is usually the better one), but you can ask staff to clarify if necessary._
> 
> **2. Download your drivers from the manufacturers site** Depending on what you read before, you likely need drivers from either AMD, Intel, or NVIDIA
> 
> **AMD**: https://www.amd.com/en/support **Intel**: https://www.intel.com/content/www/us/en/download-center/home.html **NVIDIA**: https://www.nvidia.com/Download/index.aspx?lang=en-us
> 
> **Note:**
> 
> * _For NVIDIA you want to select "Game Ready Driver (GRD)" (this is the default option) for the best performance. Once installing you'd probably prefer downloading GeForce Experience, which will notify you when there's an available drivers update._
> * _For Intel, you probably want to press "Get Started" under the "Automatically update your drivers and software", which will simplify the process and update everything automatically_
> * _For AMD you probably want to just press "Download Windows Drivers", which will download something called AMD Adrenaline, which will update your drivers automatically._
> 
> **3. Run the installation, restart your computer, and try playing MC again**
> 
> * At this point, hopefully your Minecraft is running. If it still does not work, please post any new logs and staff will help assist you with finding the right solution.

Thank you for your reply but the issue still stands. I updated my graphics driver, restarted my pc, tried to run minecraft on both CurseForge and ATLauncher but again it didn't work. I looked online and it also said to update my graphics driver. I use NVIDIA 3050 Ti if that helps. And one more thing, I used the NVIDIA app and not GeForce Experience so I don't know if that's the reason.

**Comment by chorbintime** [comment]
you need to update via the vendors website, not the app
