### ISSUE TITLE
StackOverflowError during server startup, possible corrupted world

### ISSUE THREAD

**Issue by hxllv** [LunaPixelStudios/Better-MC#1929]
### Describe the Bug

Have a server on HostHavoc that ran BetterMC v34 (got upgraded to v34.5 as part of debugging), that started hanging during scheduled restarts. Very rarely, the startup succeeds and world can be played as normal. It seems to be related to our specific world, as creating a new world makes it work fine.

No crash report gets generated. Saved logs also didn't seem to contain any useful data. In the Multicraft console, 1057 ish lines usually got skipped. Trying to run a server locally uncovered these skipped lines as the cause of the crash, with a huge stack trace (linked in the pastebin). I predict there might have been something recursive going on, but I was not able to determine the root cause. Tried to dig around region and entity data with NBTStudio, but didn't really find anything of note.

Initially it used forge version 47.3.12, but I downgraded to 47.3.0 as part of debugging, to no avail.

Serene seasons and serene seasons fix was removed from the mods list. Also notably (and I am 80% sure that it comes from these), we had a few extra mods installed:
- gravestone-forge-1.20.1-1.0.24
- Rats-1.20.1-8.1.2
- plushies-1.4.0-forge
- additional_lights-1.20.1-2.1.7
- fairylights-7.0.0-1.20.1
- smallships-forge-1.20.1-2.0.0-b1.4

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/GqAZdx22

### Operating System

Some linux distro - HostHavoc

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v34

### Other Mods

Removed
- Serene seasons
- Serene seasons fix

Added
+ gravestone-forge-1.20.1-1.0.24
+ Rats-1.20.1-8.1.2
+ plushies-1.4.0-forge
+ additional_lights-1.20.1-2.1.7
+ fairylights-7.0.0-1.20.1
+ smallships-forge-1.20.1-2.0.0-b1.4

**Comment by chorbintime** [comment]
As you are using a no-name host and the issue is only happening after scheduled restarts, this is almost 100% an issue with your server host. You also added a lot of mods, such as smallships, which tend to cause issues and be incompatible.

My best suggestion would be to try to recreate the issue on a fresh install of the modpack, and if the issue persists then report it to your server host. I have never seen this issue reported before, and I have never seen this server host before, so I'm inclined to believe there is a correlation.
