### ISSUE TITLE
Spirit mod breaking game.

### ISSUE THREAD

**Issue by Kooghi** [LunaPixelStudios/Better-MC#569]
### Describe the Bug

About an hour ago, I was looting some pyramids and was breaking the spawners inside, as I went to see what the broken spawners could do, it froze my game causing it not to respond and crash. I then re loaded and clicked on a soul spawner from the spirit mod as well and It did the same exact thing. 

### Reproduction Steps

1. Brake spawner 
2. See uses of said spawner 
3. Freezes game

### Operating System

Window 11

### Minecraft Version

1.18

### Modloader

Forge

### Modpack Version

bmc v14

### Optifine

I used Optifine

### Other Mods

I added cyclic and apotheosis and create.

**Comment by SHXRKIIE** [comment]
Need the crash report or latest.log

**Comment by xjslay** [comment]
I'm also having the exact same issue. Here's my crash report
[crash-2022-07-24_12.24.32-client.txt](https://github.com/LunaPixelStudios/Better-MC/files/9176152/crash-2022-07-24_12.24.32-client.txt)

**Comment by Web-eWorks** [comment]
Confirm the bug with an unmodified BetterMC install (with Spirit 2.1.2 and 2.1.4); I copied out Spirit and JEI into another 1.18.2 instance w/ Forge 40.1.60 and could not reproduce the crash, so it appears to be some manner of mod interaction in this modpack specifically that is responsible for the crash.

The crash can be reproduced by opening *any* Soul Engulfing recipe page and is 100% consistent.

**Comment by SHXRKIIE** [comment]
Please post the crash by uploading the file next time and not just dumping in the wall of text

**Comment by SHXRKIIE** [comment]
Wdym by "BetterMC install (with Spirit 2.1.2 and 2.1.4)", did you install a newer version to see if it fixes it?

**Comment by SHXRKIIE** [comment]
Best fix is to update the mod client and server side

**Comment by Web-eWorks** [comment]
> Wdym by "BetterMC install (with Spirit 2.1.2 and 2.1.4)", did you install a newer version to see if it fixes it?

I mean that I can confirm the crash with both the version released in the modpack (2.1.2) and the latest available release (2.1.4) and *both* versions replicate the crash. The crash is *not* resolved by updating the mod version.

Given that I was completely unable to replicate the crash in a "clean" install with just Spirit and JEI (after a significant amount of testing!), it is most likely an issue with the modpack's specific combination of mods rather than an issue intrinsic to Spirit itself.

> Best fix is to update the mod client and server side

Still crashes, does not resolve the issue.
