### ISSUE TITLE
Better Minecraft server crash 

### ISSUE THREAD

**Issue by Archive-8** [LunaPixelStudios/Better-MC#765]
### Describe the Bug

So while 2 of us were playing on a friends server, we experienced a crash (Friend was teleporting around and i made a new portal to escape the nether) We noticed all the mobs around us were frozen and didn't react to being attacked then were both kicked from the server.

The server hosting site reccomened making a new world for the server and then restarting it it, and if there are still issues to disable all mods and re-enable them one by one.

below is the crash log in pastebin and any help will be appreciated

### Reproduction Steps

1.
2.
3.
...

### Crash Report or Log

https://pastebin.com/grwYGy6T

### Operating System

Win 10

### Minecraft Version

1.16

### Modloader

Forge

### Modpack Version

v58.5

### Optifine

No

**Comment by chorbintime** [comment]
This is not a server crash. Server Watchdog, which is an internal process in all Minecraft servers, noticed your server lagged out and forcefully stopped it. Basically your server was in a vegetative state and the doctor pulled the plug to save power.

This can be fixed by preloading chunks, killing entities, and allocating more ram. I see no reason a new world would help.

You can also send a Spark profiler for me to check what on your server is using a lot of resources. Run the following command ingame:
/spark profiler --interval 100

**Comment by Rallam259** [comment]
This issue was stemmed from the wildbackport for 1.18.2. maybe the same issue for 1.16. we reverted the update and this fixed the issue. it is the exact same issue we had. something was having trouble rendering in. in our case it was an illiger at an outpost.

This could be the issue for you too.
