### ISSUE TITLE
Origin Ability

### ISSUE THREAD

**Issue by aranaei** [LunaPixelStudios/Better-MC#810]
### Describe the Bug

My origin in my server is arachnid. The ability to toggle wall climbing is "g", but after the V9 update even though I reset the key multiple times and it isn't interfering with other keybinds, it won't work.

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v9

### Optifine

I used Optifine

**Comment by chorbintime** [comment]
1) You are not using Optifine, it's a forge mod and is incompatible with every modpack that doesn't state otherwise. Do not use Optifine. Nonetheless, it doesn't matter here since Fabric doesn't load Forge mods.

2) Try binding it to a different key. If that doesn't work, make sure you are still the Archanid origin by pressing O ingame.
