### ISSUE TITLE
Unable to Plant Crops on Rich Soil Farmland

### ISSUE THREAD

**Issue by Atsumachi** [LunaPixelStudios/Better-MC#838]
### Describe the Bug

Currently it is impossible to plant any new crops onto the Rich Soil Farmland from _Farmer's Delight_ mod. Rice and Tomatoes are able to survive on the block but any other crop that, once harvested from the block, will cease to be able to be replanted. Likewise, using right-click harvest on any crops on said block will also completely uproot the seeds and will be unable to be replanted (barring Rice and Tomatoes).

### Reproduction Steps

1. Harvest existing crops from Rich Soil Farmland (right-click or destroying crops)
2. Right-click to re-plant crops (Wheat Seed, Potato, etc.)
3. Unable to plant new crops.

### Screenshots and Videos

![2022-11-05_12 35 50](https://user-images.githubusercontent.com/89116003/200135879-b975d818-e139-408f-8260-5e04b4dc8fb1.png)

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v10

### Optifine

No

**Comment by chorbintime** [comment]
Nothing we can do about this. It's an issue with the Farmer's Delight mod. You can report it on their Github.

**Comment by chorbintime** [comment]
This appears to be an issue with the Paradise Lost mod. Please try removing this mod and see if the issue persists.

I apologize for any confusion.

**Comment by Zifiv** [comment]
Like @andres-urquieta said, it's an incompatibility with MoreTags and Farmer's Delight.

MoreTags breaks all others mixins applied on the "canPlantOnTop" method of "PlantBlock" because he cancel the return and do his own.

So it should be added as a default datapack to add Rich Soil Farmland in the tag "c:farmland" until I make the update to add the compatibility with this bad mod MoreTags... (seriously use mixins to break others mods... this is not a good way to code with Fabric...).
