### ISSUE TITLE
Invalid player data

### ISSUE THREAD

**Issue by igisek** [LunaPixelStudios/Better-MC#845]
### Describe the Bug

I've just loaded my better Minecraft and I wanted to play on my single player world, and before connecting to the world I get an error saying invalid player data. (I use curse forge to run the mod). Please help, I am also very scared of loosing progress in my worlds. 
I have the version 1.19.2 v10 and it says fabric by it.

I have been using this for a month and everything has been working fine and smoothly until today.

### Reproduction Steps

1.
2.
3.
...

### Screenshots and Videos

![Better mc issue](https://user-images.githubusercontent.com/117685378/200412397-fa8dd498-e774-4460-b716-4833965fbd80.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

v10

### Optifine

No

**Comment by cory4patriots** [comment]
I just had this issue as well.. PLEASE HELP

**Comment by SmolBraino** [comment]
Got this too, same version but on MAC OS.

**Comment by ryhnochaser09** [comment]
This was working 10 hours ago last night no issue and this issue.  Also noticed that I got the standard Mojang splash screen during loading and the menu screen was back to standard as well (no Fabric Better MC logo) ... also there were additional menus at the top of the screen.
My world is unplayable... please fix this

**Comment by Coronado-Rafael-Unilu** [comment]
Hello Windows 10 user here, I have the same issue, the load screen is also the default Mojang one, last time it worked was 13h ago, I tried re-installing and making a new world to no avail

**Comment by iturbz** [comment]
Yeah I’ve had the exact same issue I tried everything going off backups even just deleting all data and reinstalling the game and the mod pack to get the same issue all over again

**Comment by domxx9** [comment]
It appears to be due to #846

**Comment by iturbz** [comment]
> It appears to be due to #846

I have deleted the illuminations mod just to see if there is and change and comes up with yet the same invalid player data but no pop up

**Comment by Bobzouz** [comment]
Same issue since today, worked perfectly yesterday

**Comment by Scinexx** [comment]
> Same issue since today, worked perfectly yesterday

Yes, my game worked fine yesterday as well!

**Comment by iturbz** [comment]
So I have been on the curseforge discord and it seems to be an issue with the new Minecraft launcher update which has messed up the forge app there isn’t a proper fix yet I believe so just hold on and keep an eye out

**Comment by Scinexx** [comment]
> So I have been on the curseforge discord and it seems to be an issue with the new Minecraft launcher update which has messed up the forge app there isn’t a proper fix yet I believe so just hold on and keep an eye out

Ah I see, thanks for the heads up

**Comment by iturbz** [comment]
It’s messed up all modpacks pretty much not just this one

**Comment by Scinexx** [comment]
Theres a temporary fix if you make your way to the CursedForge discord. in the #server-issues channel. doesn't work for everyone apparently, but it worked for me!

**Comment by chorbintime** [comment]
There is currently an issue where configs are not being loaded because of Microsoft's changes to the Minecraft launcher. You may cause permanent damage to your world because of this.

The only known, permanent fix to this is to switch to GDLauncher. It is substantially better than Curseforge and it's very easy to transfer your Curseforge save:
1) First, install GDLauncher from here https://gdlauncher.com/en/download/. Once the launcher is installed, click the Plus icon at the bottom left of the launcher and search for the modpack you want to play. After it's installed, you'll see a menu about opted out mods. Click continue.
2) Right click the modpack in Curseforge, Open Folder
3) Do the same thing on GDLauncher
4) Drag the saves folder in the Curseforge files to the GDLauncher files. Drag over the Xaero's Minimap or Journeymap folder aswell.

The reason GDLauncher works and Curseforge doesn't is because GDLauncher does not open the Minecraft Launcher when you open a modpack. You will have the exact same modpack from GDL as you would on Curseforge, so you'll still be able to join the same servers.

**Comment by ryhnochaser09** [comment]
I followed the recommendation above however the GDLaucher is not allowing Microsoft logins and seems related to this issue https://github.com/gorilla-devs/GDLauncher/issues/1449
