### ISSUE TITLE
Mod Discontinued

### ISSUE THREAD

**Issue by woodedrune** [LunaPixelStudios/Better-MC#846]
### Describe the Bug

The Illumination Mod is soon to be discontinued and merged with Effective. This is interfering with Better MC loading. 

### Reproduction Steps

1. Open Better MC from CurseForge App
2. Click Play, Game Starts Up
3. Banner Stating Illumination is merging with Essential
4. Better MC is not loaded and won't play worlds made with BMC
...

### Screenshots and Videos

![Screenshot 2022-11-07 160733](https://user-images.githubusercontent.com/117686082/200415935-33c5472e-3a43-4a5c-8230-61eefc4693db.png)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

bmc 1.19.2 v10

### Optifine

No

**Comment by domxx9** [comment]
This is the same as reported in #845 however includs more information needs to be merged

**Comment by chorbintime** [comment]
This is not an issue with Effective.


There is currently an issue where configs are not being loaded because of Microsoft's changes to the Minecraft launcher. You may cause permanent damage to your world because of this.

The only known, permanent fix to this is to switch to GDLauncher. It is substantially better than Curseforge and it's very easy to transfer your Curseforge save:
1) First, install GDLauncher from here https://gdlauncher.com/en/download/. Once the launcher is installed, click the Plus icon at the bottom left of the launcher and search for the modpack you want to play. After it's installed, you'll see a menu about opted out mods. Click continue.
2) Right click the modpack in Curseforge, Open Folder
3) Do the same thing on GDLauncher
4) Drag the saves folder in the Curseforge files to the GDLauncher files. Drag over the Xaero's Minimap or Journeymap folder aswell.

The reason GDLauncher works and Curseforge doesn't is because GDLauncher does not open the Minecraft Launcher when you open a modpack. You will have the exact same modpack from GDL as you would on Curseforge, so you'll still be able to join the same servers.
