### ISSUE TITLE
Error when connecting to server

### ISSUE THREAD

**Issue by elnatoo** [LunaPixelStudios/Better-MC#937]
### Describe the Bug

Hi all,

So I was amidst doing a raid to defend the honor of my village when suddenly I got kicked out of my server (I'm playing on an Aternos hosted server for BMC 1.19.2 v11) and got the error message shown in the attached screenshot. Is there any way to fix this? I am literally unable to re-enter the server at all without getting the error after the terrain loading.

### Reproduction Steps

1. Attempt to Log into server
2. Stuck on loading...
3. Get error
...

### Screenshots and Videos

![screen2](https://user-images.githubusercontent.com/68631758/209281591-f9773f09-ba41-4943-8537-9f02e1f4286c.PNG)

### Crash Report or Log

https://pastebin.com/DKtUscN6

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

BMC v11

### Optifine

No

### Other Mods

None

**Comment by chorbintime** [comment]
Stop using Aternos. I am unable to properly assist Aternos users for a multitude of reasons. It's possible that this issue is completely unfixable until you stop using Aternos.

You can download the serverpack from the modpack's Curseforge page and host that way instead. Feel free to transfer your world save, if Aternos lets you download it from them.

**Comment by elnatoo** [comment]
I got the world data downloaded and attempted to run the serverpack on PowerShell but got greeted by this error. :/
![screen3](https://user-images.githubusercontent.com/68631758/209408878-ffd3a9b8-6813-4433-b402-7d56c8fc00a6.PNG)

**Comment by chorbintime** [comment]
You need Java 17 or 18 for 1.19.2

Please read the readme file
